from views.dashboard import DashboardWidget, WelcomeScreen
from views.comuni import ElencoComuniWidget, InserimentoComuneWidget
from views.partite import RicercaPartiteWidget, InserimentoPartitaWidget, OperazioniPartitaWidget
from views.possessori_immobili import InserimentoPossessoreWidget, RicercaAvanzataImmobiliWidget, RegistrazioneProprietaWidget
from views.localita import InserimentoLocalitaWidget
from views.amministrazione import GestioneUtentiWidget, AuditLogViewerWidget, BackupWidget, GestionePeriodiStoriciWidget, GestioneTipiLocalitaWidget, GestioneTitoliPossessoWidget, RegistraConsultazioneWidget
from views.strumenti import EsportazioniWidget, ReportisticaWidget, StatisticheWidget
from views.ricerca import UnifiedFuzzySearchThread, UnifiedFuzzySearchWidget
